"""Compatibility facade for ORM models.

Runtime code should import from the owning module. This facade also gives
Alembic one stable import that registers every mapped class.
"""

from modules.admin.models import Admin, AdminSession, AdminStatus
from modules.auth.models import (
    Organization,
    OrganizationDomain,
    OrganizationExperience,
    OrganizationFeatureEntitlement,
    OrganizationProfile,
    OrganizationType,
    Session,
    User,
    UserRole,
    UserStatus,
)
from modules.restaurant.models import (
    Cart,
    CartProduct,
    CartProductCustomization,
    Category,
    Coupon,
    CustomerBillingAddress,
    CustomerLoyalty,
    Ingredient,
    Invoice,
    Media,
    MediaVariant,
    Order,
    OrderProduct,
    Payment,
    Product,
    ProductCustomizationOption,
    ProductIngredient,
    ProductMedia,
    ProductReview,
    ReviewReaction,
    ReviewReply,
    SiteSetting,
)

__all__ = [
    "Admin",
    "AdminSession",
    "AdminStatus",
    "Cart",
    "CartProduct",
    "CartProductCustomization",
    "Category",
    "Coupon",
    "CustomerBillingAddress",
    "CustomerLoyalty",
    "Ingredient",
    "Invoice",
    "Media",
    "MediaVariant",
    "Order",
    "OrderProduct",
    "Organization",
    "OrganizationDomain",
    "OrganizationExperience",
    "OrganizationFeatureEntitlement",
    "OrganizationProfile",
    "OrganizationType",
    "Payment",
    "Product",
    "ProductCustomizationOption",
    "ProductIngredient",
    "ProductMedia",
    "ProductReview",
    "ReviewReaction",
    "ReviewReply",
    "Session",
    "SiteSetting",
    "User",
    "UserRole",
    "UserStatus",
]
