import { test, expect } from '@playwright/test'

for (const viewport of [{ width: 1440, height: 1000 }, { width: 390, height: 844 }]) {
  test.describe(`${viewport.width}px`, () => {
    test.use({ viewport })
    test.beforeEach(async ({ page }) => {
      await page.addInitScript(() => {
        if (!localStorage.getItem('bonefree_locale')) localStorage.setItem('bonefree_locale', 'en-GB')
        localStorage.setItem('bonefree:admin_token', 'legal-browser-owner')
        localStorage.setItem('bonefree:admin_role', 'owner')
        localStorage.setItem('bonefree:admin_name', 'Browser Owner')
        localStorage.setItem('bonefree:cookie_consent', JSON.stringify({ accepted: true, version: 1, acceptedAt: new Date().toISOString() }))
        sessionStorage.setItem('bonefree:prototype_notice_dismissed', 'true')
      })
    })

    test('public pages render all languages and the same current contact', async ({ page }, testInfo) => {
      for (const locale of ['en-GB', 'pt-PT', 'de-DE']) {
        await page.goto('/privacy')
        await page.evaluate(value => localStorage.setItem('bonefree_locale', value), locale)
        await page.reload()
        await expect(page.locator('.legal-shell')).toHaveAttribute('lang', locale)
        await expect(page.locator('.legal-content')).toContainText('carambolarubra@gmail.com')
        await expect(page.locator('.legal-content')).not.toContainText('{{organization_')
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
        await page.screenshot({ path: testInfo.outputPath(`privacy-${locale}.png`), fullPage: true })
        await page.goto('/terms')
        await expect(page.locator('.legal-shell')).toHaveAttribute('lang', locale)
        await expect(page.locator('.legal-content')).toContainText('carambolarubra@gmail.com')
      }
    })

    test('owner edits, keeps translations across switches and publishes immediately', async ({ page }, testInfo) => {
      await page.goto('/admin/dashboard?tab=privacy')
      await page.locator('[data-privacy-nav-section="policy"]').click()
      const policy = page.locator('#data-privacy-policy .legal-document-editor')
      await expect(policy.getByLabel('Title', { exact: true })).toBeVisible()
      const title = `Published policy ${viewport.width}`
      await policy.getByLabel('Title', { exact: true }).fill(title)
      await policy.getByRole('button', { name: 'Document language', exact: true }).click()
      await page.getByRole('option', { name: 'Português', exact: true }).click()
      await expect(policy.getByLabel('Title', { exact: true })).toHaveValue('Política de Privacidade')
      await policy.getByRole('button', { name: 'Document language', exact: true }).click()
      await page.getByRole('option', { name: 'English', exact: true }).click()
      await expect(policy.getByLabel('Title', { exact: true })).toHaveValue(title)
      const editor = policy.getByRole('textbox', { name: 'Document content' })
      await expect(editor).toContainText('carambolarubra@gmail.com')
      await editor.scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath('editor.png'), fullPage: true })
      await editor.click()
      await page.keyboard.press('Control+End')
      await page.keyboard.press('Enter')
      await page.keyboard.type('Browser publication check.')
      await page.keyboard.press('Enter')
      await policy.getByRole('button', { name: 'Numbered list', exact: true }).click()
      await page.keyboard.type('A numbered item.')
      await policy.getByRole('button', { name: 'Preview', exact: true }).click()
      await expect(policy.locator('.legal-editor-preview')).toContainText('Browser publication check.')
      await policy.locator('.legal-editor-preview').scrollIntoViewIfNeeded()
      await page.screenshot({ path: testInfo.outputPath('editor-preview.png'), fullPage: true })
      await page.route('**/admin/legal-documents/privacy_policy/en-GB', route => route.fulfill({ status: 503, body: '{}' }), { times: 1 })
      await policy.getByRole('button', { name: 'Save and publish', exact: true }).click()
      await expect(policy.getByRole('alert')).toContainText('Publication failed')
      await expect(policy.locator('.legal-editor-preview')).toContainText('Browser publication check.')
      await policy.getByRole('button', { name: 'Save and publish', exact: true }).click()
      await expect(policy.getByRole('status')).toHaveText('Published successfully')
      await page.goto('/privacy')
      await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
      await expect(page.locator('.legal-content')).toContainText('Browser publication check.')
      await expect(page.locator('.legal-content ol').last()).toContainText('A numbered item.')
    })

    test('the saved privacy contact is shared by both public documents', async ({ page }) => {
      await page.goto('/admin/dashboard?tab=privacy')
      await page.locator('[data-privacy-nav-section="policy"]').click()
      const contact = page.getByRole('textbox', { name: 'Privacy contact email', exact: true })
      await expect(contact).toHaveValue('carambolarubra@gmail.com')
      await contact.fill('legal@example.com')
      await page.getByRole('button', { name: 'Save contact', exact: true }).click()
      await expect(page.locator('#data-privacy-policy .tiptap')).toContainText('legal@example.com')
      for (const path of ['/privacy', '/terms']) {
        await page.goto(path)
        await expect(page.locator('.legal-content')).toContainText('legal@example.com')
        await expect(page.locator('.legal-content')).not.toContainText('carambolarubra@gmail.com')
      }
      await page.goto('/admin/dashboard?tab=privacy')
      await page.locator('[data-privacy-nav-section="policy"]').click()
      await contact.fill('carambolarubra@gmail.com')
      await page.getByRole('button', { name: 'Save contact', exact: true }).click()
      await expect(page.locator('#data-privacy-policy .tiptap')).toContainText('carambolarubra@gmail.com')
    })

    test('Portuguese toolbar has styled dropdowns, accessible icons and preserves the caret', async ({ page }, testInfo) => {
      await page.addInitScript(() => localStorage.setItem('bonefree_locale', 'pt-PT'))
      await page.goto('/admin/dashboard?tab=privacy')
      await page.locator('[data-privacy-nav-section="policy"]').click()
      await expect(page.locator('#data-privacy-policy')).toContainText('Este email aparece na Política de Privacidade e nos Termos e Condições.')
      const policy = page.locator('#data-privacy-policy .legal-document-editor')
      await expect(policy.locator('select')).toHaveCount(0)
      await policy.getByRole('button', { name: 'Idioma do documento', exact: true }).click()
      await expect(page.getByRole('option', { name: 'Deutsch', exact: true })).toBeVisible()
      await page.getByRole('option', { name: 'English', exact: true }).click()
      const editor = policy.getByRole('textbox', { name: 'Conteúdo do documento' })
      const toolbar = policy.getByRole('toolbar')
      await editor.click()
      await page.keyboard.press('Control+End')
      await page.keyboard.press('Enter')
      await toolbar.getByRole('button', { name: 'Estilo do texto' }).click()
      for (const name of ['Parágrafo', 'Título de secção', 'Subtítulo']) {
        await expect(page.getByRole('option', { name, exact: true })).toBeVisible()
      }
      await page.getByRole('option', { name: 'Subtítulo', exact: true }).click()
      await expect(editor).toBeFocused()
      await page.keyboard.type('Toolbar check')
      await expect(editor.locator('h3').last()).toContainText('Toolbar check')
      const bold = toolbar.getByRole('button', { name: 'Negrito', exact: true })
      await expect(bold).toHaveAttribute('title', 'Negrito')
      await bold.click()
      await expect(bold).toHaveAttribute('aria-pressed', 'true')
      await page.keyboard.type(' formatted')
      await expect(editor.locator('strong').last()).toContainText('formatted')
      await expect(toolbar.getByRole('button', { name: 'Itálico', exact: true })).toHaveAttribute('title', 'Itálico')
      const variableCount = await editor.locator('[data-organization-variable]').count()
      await toolbar.locator('summary').click()
      await expect(toolbar.getByRole('button', { name: /Nome da organização/ })).toBeVisible()
      await toolbar.getByRole('button', { name: /Email de contacto/ }).click()
      await expect(editor.locator('[data-organization-variable]')).toHaveCount(variableCount + 1)
      await expect(editor).toBeFocused()
      await expect(toolbar.locator('details')).not.toHaveAttribute('open', '')
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      await toolbar.evaluate(element => {
        const container = element.closest('.ad-main')
        const header = document.querySelector('.data-privacy-sticky-header')
        if (container && header) container.scrollTop += element.getBoundingClientRect().top - header.getBoundingClientRect().bottom - 16
      })
      await toolbar.screenshot({ path: testInfo.outputPath('toolbar-pt.png') })
    })
  })
}
